### ISSUE TITLE
Update the Profile-table with a photo column 

### ISSUE THREAD

**Issue by eyvmal** [boolean-uk/team-dev-server-ex-2410-team2#11]
Description:
To allow users to save profile pictures, the Profile-table must be updated with a new photo-column.  The schema.prisma, seed.js, user.js, and openapi.yml must be updated accordingly.

What to do:
* Add a photo column in the Profile-table
* Update schema.prisma, seed.js, user.js, and openapi.yml

Additional info:
Currently the frontend is set up to encode the images with base64, which converts the image into a string to be stored in the postgres database. However, this may end up creating quite long strings and MAY lead to difficulties with payload-sizes when transmitting data over the API.

![Image](https://github.com/user-attachments/assets/17c0a9a6-8546-4f97-80c5-9516e9faaca2)

**Comment by JHalvor** [comment]
approve please @uerbzr
