### ISSUE TITLE
Create CRUD functionality for "Post" domain and endpoints

### ISSUE THREAD

**Issue by Muzea001** [boolean-uk/team-dev-server-ex-2410-team2#14]

**Comment by JHalvor** [comment]
Parent EPIC: https://github.com/boolean-uk/team-dev-client-ex-2410-team2/issues/6

**Comment by JHalvor** [comment]
approve please @uerbzr

**Comment by eyvmal** [comment]
Add the missing CRUD operations for the Post-object.
- Create
- GetAll
- GetById
- Delete

(UpdateById is created in another issue)

**Comment by eyvmal** [comment]
Added new endpoints for:
- getById
- updateById
- deleteById

Updated endpoints for:
- create
- getAll

New files:
- domain/post.js

Updated files:
- routes/post.js
- controllers/post.js
- docs/openapi.yml
---
All endpoints require the user to be logged in.

getById fetches a post with an id input parameter.
updateById updates a post with an id input parameter and content body.
deleteById deletes a post with and id input parameter.
create creates a new post for the logged in user with a content body.
getAll fetches all posts.

the domain/post.js file contains all database calls, and follows the format of the already existing domain/user.js.
the controllers/post.js file is updated with all endpoint logic and error handling.
the docs/openapi.yml is updated with the new endpoints and a new UpdatePost-schema.
