### ISSUE TITLE
Add password validation for server side

### ISSUE THREAD

**Issue by tvaltn** [boolean-uk/team-dev-server-ex-2410-team2#2]
Add password validation for the user in the backend, following these requirements:
* The password should not be less than 8 characters in length
* The password should contain at least one uppercase character
* The password should contain at least one number
* The password should contain at least one special character

Parent Epic: https://github.com/boolean-uk/team-dev-client-ex-2410-team2/issues/2

[Figma Board](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=228-41540)

**Comment by JHalvor** [comment]
approve please @uerbzr

**Comment by Ingeborgausteid** [comment]
@JHalvor @uerbzr 
Pull request ready for review.

**Comment by JHalvor** [comment]
replied to your pr:
user field validations should be in src > middleware > auth i suggest creating a validateUserFields or validateUserInputs function that will be called from create and update/patch routes for users src > routes> user.
This function can contain validation for both password and email
