### ISSUE TITLE
Create get endpoints for Cohort.

### ISSUE THREAD

**Issue by Muzea001** [boolean-uk/team-dev-server-ex-2410-team2#31]
Implement endpoint for getting all cohorts from the Db.
- Create the endpoint get all cohorts in the cohort.ts file in the controller folder.
- Create the endpoint to get a cohort by its teacherId in the controller folder.
-  Create the endpoint to get a cohort by its studentId in the controller folder.
- Update the OpenApi.yaml file to contain the new endpoint.
- Test endpoint by fetching some seeded cohorts

**Comment by Muzea001** [comment]
Fetching a cohort should include all the students that are contained in it.

**Comment by eyvmal** [comment]
Modified:
- controllers/cohort.js
- domain/cohort.js
- routes/cohort.js
- docs/openapi.yml
---
The routes file has been updated with the new get routes.
The controller file has been updated with new get methods.
The domain file has been updated with new db interactions for the new get methods.
The openapi has been updated with swagger doc for the new get endpoints, and also updated with a new Cohort object schema.
