### ISSUE TITLE
Create Edit/Delete endpoints for cohorts

### ISSUE THREAD

**Issue by Muzea001** [boolean-uk/team-dev-server-ex-2410-team2#32]
- Create endpoints in the controller for editing and deleting a cohort
- Make sure to call validateTeacher in the route to the endpoint, only a teacher should be able to edit/delete a cohort.
- Update the openAPI.yaml spec so it contains the newly added endpoints.
- Test the endpoint in swagger.

**Comment by eyvmal** [comment]
Modified:
- routes/cohort.js
- controllers/cohort.js
- domain/cohort.js
- docs/openapi.yml
---
The routes have been created for patch and delete, and protected by TEACHER role.
The controller has been modified to handle the new endpoints
The domain has been modified to handle the new endpoints
The openapi docs has been modified with swagger documentation for the new endpoints.
