### ISSUE TITLE
Update the User/Profile table with relevant columns

### ISSUE THREAD

**Issue by tvaltn** [boolean-uk/team-dev-server-ex-2410-team2#4]
Add missing columns to the User or Profile table.
What to do:
- Update the schema.prisma
- Update the seed.js
- Update domain/user.js
- Update openapi.yml (API Spec)

For locked values, just add the default value shown in the figma/attached image

Currently missing:
- Username
- Mobile
- Specialism (LOCKED)
- Start Date (LOCKED)
- End Date (LOCKED)
- Photo (Maybe skip for now, add another issue later?)

Parent Epic: boolean-uk/team-dev-client-ex-2410-team2#2

[Figma Board](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=204-8131)

![Image](https://github.com/user-attachments/assets/76503ff0-4eea-4882-b6cf-f4a91d893aef)

**Comment by uerbzr** [comment]
👍👍
