### ISSUE TITLE
Implement endpoint for getting a user through postId

### ISSUE THREAD

**Issue by Muzea001** [boolean-uk/team-dev-server-ex-2410-team2#7]

**Comment by JHalvor** [comment]
Relevant for getting a user Firstname and lastname and initials for given post

![Image](https://github.com/user-attachments/assets/58b90250-2d38-4a02-8642-5ca162a60362)

**Comment by JHalvor** [comment]
approve please @uerbzr

**Comment by JHalvor** [comment]
NOT NECESSARY! post already have a relation to a user
