### ISSUE TITLE
Generate prisma table for comments with the following fields : "commentId, userId, postId,"content"

### ISSUE THREAD

**Issue by Muzea001** [boolean-uk/team-dev-server-ex-2410-team2#8]
Create a prisma table for "comment". Each post should contain a list of comments, with a foreign key "postId" on each comment. The comment table should contain then a commentId, a postId and a userId, in addition to the actual comment text.

**Comment by JHalvor** [comment]
approve please @uerbzr

**Comment by Muzea001** [comment]
- Change post table in prisma so it contains a list of comments (one to many).
- Create comments table with commendId, postId, userId and content.
- Change post domain and endpoint so that fetching of posts includes comments. 
- Run the migration and test create some comments.![Image](https://github.com/user-attachments/assets/edf5347e-116f-4313-93c5-7b3513a59b03)
